# Multi-tier application with rich labeling scheme
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-v1
  labels:
    app: ecommerce
    tier: frontend
    version: v1
    environment: production
    team: web
    component: ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ecommerce
      tier: frontend
      version: v1
  template:
    metadata:
      labels:
        app: ecommerce
        tier: frontend
        version: v1
        environment: production
        team: web
        component: ui
    spec:
      containers:
      - name: frontend
        image: temitayocharles/hello-k8s:latest
        ports:
        - containerPort: 80
        env:
        - name: VERSION
          value: "v1"
        - name: TIER
          value: "frontend"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-v2
  labels:
    app: ecommerce
    tier: frontend
    version: v2
    environment: staging
    team: web
    component: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce
      tier: frontend
      version: v2
  template:
    metadata:
      labels:
        app: ecommerce
        tier: frontend
        version: v2
        environment: staging
        team: web
        component: ui
        track: canary
    spec:
      containers:
      - name: frontend
        image: temitayocharles/hello-k8s:latest
        ports:
        - containerPort: 80
        env:
        - name: VERSION
          value: "v2"
        - name: TIER
          value: "frontend"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-v1
  labels:
    app: ecommerce
    tier: api
    version: v1
    environment: production
    team: backend
    component: service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce
      tier: api
      version: v1
  template:
    metadata:
      labels:
        app: ecommerce
        tier: api
        version: v1
        environment: production
        team: backend
        component: service
    spec:
      containers:
      - name: api
        image: temitayocharles/hello-k8s:latest
        ports:
        - containerPort: 80
        env:
        - name: VERSION
          value: "v1"
        - name: TIER
          value: "api"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: ecommerce
    tier: database
    version: v1
    environment: production
    team: data
    component: storage
    criticality: high
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce
      tier: database
  template:
    metadata:
      labels:
        app: ecommerce
        tier: database
        version: v1
        environment: production
        team: data
        component: storage
        criticality: high
    spec:
      containers:
      - name: database
        image: temitayocharles/hello-k8s:latest
        ports:
        - containerPort: 80
        env:
        - name: TIER
          value: "database"
