# ServiceAccount: Identity for pods
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-reader
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-admin
  namespace: default
---
# Pod using custom ServiceAccount
apiVersion: v1
kind: Pod
metadata:
  name: reader-pod
  labels:
    app: rbac-demo
spec:
  serviceAccountName: app-reader
  containers:
  - name: kubectl
    image: bitnami/kubectl:latest
    command: ['sh', '-c', 'sleep 3600']
---
apiVersion: v1
kind: Pod
metadata:
  name: admin-pod
  labels:
    app: rbac-demo
spec:
  serviceAccountName: app-admin
  containers:
  - name: kubectl
    image: bitnami/kubectl:latest
    command: ['sh', '-c', 'sleep 3600']
