# Intentionally BROKEN Role - missing critical permissions
# Use this to practice debugging RBAC issues
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: broken-pod-manager
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]  # ⚠️ PROBLEM: Missing "create", "delete" verbs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: broken-pod-manager-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: broken-pod-manager
subjects:
- kind: ServiceAccount
  name: app-reader
  namespace: default
---
# FIXED version (apply this after debugging)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fixed-pod-manager
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "delete", "update", "patch"]  # ✅ All needed verbs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fixed-pod-manager-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fixed-pod-manager
subjects:
- kind: ServiceAccount
  name: app-reader
  namespace: default
