# NodePort Service (External Access via Node IP:Port)
apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
  labels:
    app: web
    type: external-dev
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - name: http
    port: 80        # Service port (internal)
    targetPort: 80  # Container port
    nodePort: 30080 # External port (30000-32767 range)
    protocol: TCP
